name: Hello         # ワークフロー名
on: push           # イベント（プッシュ時に起動）
jobs:              # ジョブの定義
  hello:           # ジョブID
    timeout-minutes: 5   # タイムアウト時間（5分）
    runs-on: ubuntu-latest   # ランナー（Ubuntuで実行）
    defaults:
      run:
        shell: bash       # デフォルトのシェルを Bash に指定
    steps:                 # ステップの定義
      - name: Run a command   # ステップの名前
        run: echo "Hello, world"  # シェルコマンドの実行
      - uses: actions/checkout@v4   # アクションの呼び出し